-- /sql/01_create_tables.sql
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.SALES;

USE DATABASE ANALYTICS_DB;
USE SCHEMA SALES;

-- Tables
CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID INTEGER,
  NAME        STRING,
  EMAIL       STRING,
  LOCATION    STRING,
  SIGNUP_DATE DATE
);

CREATE OR REPLACE TABLE PRODUCTS (
  PRODUCT_ID  INTEGER,
  NAME        STRING,
  CATEGORY    STRING,
  PRICE       NUMBER(10,2)
);

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID     INTEGER,
  CUSTOMER_ID  INTEGER,
  ORDER_DATE   DATE,
  TOTAL_AMOUNT NUMBER(12,2)
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
  ITEM_ID    INTEGER,
  ORDER_ID   INTEGER,
  PRODUCT_ID INTEGER,
  QUANTITY   INTEGER,
  SUBTOTAL   NUMBER(12,2)
);

-- Optional: stage + format (if you want to show infra completeness)
CREATE OR REPLACE FILE FORMAT FF_CSV_STD
  TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE OR REPLACE STAGE STAGE_SALES FILE_FORMAT=FF_CSV_STD;
