-- /sql/02_load_data.sql
USE DATABASE ANALYTICS_DB;
USE SCHEMA SALES;

-- 1) Clean
TRUNCATE TABLE ORDER_ITEMS;
TRUNCATE TABLE ORDERS;
TRUNCATE TABLE PRODUCTS;
TRUNCATE TABLE CUSTOMERS;

-- 2) Load from stage root
COPY INTO CUSTOMERS
FROM @STAGE_SALES/customers.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR='ABORT_STATEMENT' FORCE=TRUE;

COPY INTO PRODUCTS
FROM @STAGE_SALES/products.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR='ABORT_STATEMENT' FORCE=TRUE;

COPY INTO ORDERS
FROM @STAGE_SALES/orders.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR='ABORT_STATEMENT' FORCE=TRUE;

COPY INTO ORDER_ITEMS
FROM @STAGE_SALES/order_items.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"')
ON_ERROR='ABORT_STATEMENT' FORCE=TRUE;

-- 3) Verify counts
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM CUSTOMERS
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS
UNION ALL SELECT 'ORDERS',   COUNT(*) FROM ORDERS
UNION ALL SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS;

-- 4) Peek data
SELECT * FROM CUSTOMERS LIMIT 5;
SELECT * FROM PRODUCTS LIMIT 5;
SELECT * FROM ORDERS LIMIT 5;
SELECT * FROM ORDER_ITEMS LIMIT 5;
