-- /sql/03_create_view.sql
USE DATABASE ANALYTICS_DB;
USE SCHEMA SALES;

CREATE OR REPLACE VIEW SALES_SUMMARY AS
SELECT
  o.ORDER_ID,
  o.ORDER_DATE,
  c.CUSTOMER_ID,
  c.NAME      AS CUSTOMER_NAME,
  c.LOCATION  AS CUSTOMER_LOCATION,
  p.PRODUCT_ID,
  p.NAME      AS PRODUCT_NAME,
  p.CATEGORY,
  oi.QUANTITY,
  oi.SUBTOTAL AS ORDER_VALUE
FROM ORDERS o
JOIN CUSTOMERS c    ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN ORDER_ITEMS oi ON oi.ORDER_ID   = o.ORDER_ID
JOIN PRODUCTS p     ON p.PRODUCT_ID  = oi.PRODUCT_ID;

-- Quick sanity
SELECT * FROM SALES_SUMMARY LIMIT 10;
